export const Departments = {
    ALL: 'all',
    ANDROID: 'android',
    IOS: 'ios',
    DESIGN: 'design',
    MANAGEMENT: 'management',
    QA: 'qa',
    BACK_OFFICE: 'back_office',
    FRONTEND: 'frontend',
    HR: 'hr',
    PR: 'pr',
    BACKEND: 'backend',
    SUPPORT: 'support',
    ANALYTICS: 'analytics',
}
